baseURL: https://mikeder.net/
languageCode: en-us
title: mikeder.net
sectionPagesMenu: main
enableGitInfo: true


taxonomies:
  category: categories
  tag: tags

params:
  description: A static site built with Hugo!
  author: Mike Eder

  bandcampuser: mikeder
  githubuser: mikeder
  instagramuser: sqweebking
  mastodonURL: https://universeodon.com/@sqweebking
  soundclouduser: sqweebking
  youtubeuser: synthatik
  dockerhubuser: mikeder
