baseURL = "https://mikeder.net/"
languageCode = "en-us"
title = "mikeder.net"
sectionPagesMenu = "main"
enableGitInfo = true


[taxonomies]
  tag = 'tags'

[params]
    bandcampuser = "mikeder"
    githubuser = "mikeder"
    instagramuser = "sqweebking"
    soundclouduser = "sqweebking"
    youtubeuser = "synthatik"
    dockerhubuser = "mikeder"
